### ISSUE TITLE
Java 11 — Paper and ServerJars Updater

### ISSUE THREAD

**Issue by WINGS07** [PaperMC/Paperclip#29] opened 2020-12-15 09:29 UTC
on startup I get this error:
`Unable to retrieve Instrumentation API to add Paper jar to ClassPath_`

My server runs JAVA 11, [ServerJars updater](serverjars.com/updater)

After successful installation, paper starts applying patches, and after that it just crashes with this error

JVM Flags:
```
java -Xms128M -Xmx3072M -Dterminal.jline=false -Dterminal.ansi=true -Djava.system.class.loader=com.serverjars.updater.ServerJarsLoader -jar upd.jar
```

![IMG_20201215_122729_698.jpg](https://user-images.githubusercontent.com/72886646/102196411-ed487300-3ed0-11eb-8193-12e21c9050f9.jpg)

**Comment by electronicboy** [comment] 2020-12-15 09:32
This is essentially a duplicate of #28, paperclip needs to use an agent to bootstrap the server properly, this is something you'd need to take up with serverjars.

**Closed by electronicboy** 2020-12-15 09:32 UTC
