### ISSUE TITLE
Red paperclip.jar in my list of screen

### ISSUE THREAD

**Issue by wikoz209** [PaperMC/Paperclip#27] opened 2020-11-04 18:25 UTC
How i can repair this? I cant turn on my minecraft server.
![mc 3](https://user-images.githubusercontent.com/73961409/98153404-6e284e00-1ed3-11eb-85e1-b053fe7078e1.png)

**Comment by l1ttleO** [comment] 2020-11-04 18:28
1) This belongs in https://github.com/PaperMC/Paper/issues
2) Fix your file permissions

**Comment by Prof-Bloodstone** [comment] 2020-11-04 18:29
Your world files are owned by some other user most probably.
You can check it by running `ls -l`.

Since this isn't a bug, I highly recommend you joining Paper Discord for resolving issues like that :)

**Comment by rrvk** [comment] 2020-11-04 19:58
It looks like you cant acces the session.lock and if i am not wrong that long is maked if the server is already running? 
is the server not already running in that other screen?

**Comment by electronicboy** [comment] 2020-11-04 20:01
Not a paper issue in any capacity, 

The coloring of items is down to varying aspects like permissions, executability, etc...

The issue is that your file perms are wrong, please use the discord for support

**Closed by electronicboy** 2020-11-04 20:01 UTC
